name: Publish package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Code checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install poetry
      run: pip install poetry

    - name: Install environment
      run: poetry install

    - name: Run pytest and generate coverage report
      run: poetry run pytest --cov=./landsatxplore_V2 --cov-report=xml
      env:
        LANDSATXPLORE_USERNAME: ${{ secrets.LANDSATXPLORE_TEST_USERNAME }}
        LANDSATXPLORE_PASSWORD: ${{ secrets.LANDSATXPLORE_TEST_PASSWORD }}

    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Build package
      run: poetry build

    - name: Publish to Test PyPi
      run: |
        poetry config repositories.testpypi https://test.pypi.org/legacy/
        poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_TOKEN }}
        poetry publish -r testpypi

    - name: Publish to PyPi
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
        poetry publish
